// User Actions
export const ACTION_GET_USER = 'ACTION_GET_USER';
export const ACTION_GET_ALBUM = 'ACTION_SET_LOADING';
export const ACTION_GETTING_USER = 'ACTION_GETTING_USER';
export const ACTION_REMOVE_ALBUM = 'ACTION_REMOVE_ALBUM';
// Album Actions
export const ACTION_ALBUMS_GET_ALL = 'ACTION_ALBUMS_GET_ALL';
export const ACTION_ALBUMS_GET = 'ACTION_ALBUMS_GET';
export const ACTION_ALBUMS_GETTING = 'ACTION_ALBUMS_GETTING';
